"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MultiCall = exports.ERC721 = exports.ERC20 = exports.ERC1155 = void 0;
var ERC1155_1 = require("./ERC1155/ERC1155");
Object.defineProperty(exports, "ERC1155", { enumerable: true, get: function () { return ERC1155_1.ERC1155; } });
var ERC20_1 = require("./ERC20/ERC20");
Object.defineProperty(exports, "ERC20", { enumerable: true, get: function () { return ERC20_1.ERC20; } });
var ERC721_1 = require("./ERC721/ERC721");
Object.defineProperty(exports, "ERC721", { enumerable: true, get: function () { return ERC721_1.ERC721; } });
var MultiCall_1 = require("./MultiCall/MultiCall");
Object.defineProperty(exports, "MultiCall", { enumerable: true, get: function () { return MultiCall_1.MultiCall; } });
